[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "postgresql"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci", "cat prisma/schema.prisma", "npx prisma generate"]

[build.nixpacksPlan.phases.build]
cmds = ["rm -rf .next", "npm run build"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
